default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
  # Converted local hooks to managed python environments for deterministic behavior.
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        # Run directly over tools & tests; pre-commit environment supplies mypy dependency.
        entry: mypy --config-file mypy.ini tools tests
        pass_filenames: false
        stages: [pre-commit]
        additional_dependencies:
          - mypy==1.10.0
      - id: audit-type-ignores
        name: audit type ignores
        language: python
        entry: python tools/audit_type_ignores.py
        pass_filenames: false
        stages: [pre-commit]
        # No extra deps; stdlib only.
      - id: pytest-quick
        name: pytest quick subset
        language: python
        entry: pytest -q --maxfail=1
        pass_filenames: false
        stages: [pre-commit]
        # Include core runtime deps required for imports in tests.
        additional_dependencies:
          - pytest==8.3.2
          - hypothesis==6.92.0
          - numpy==1.26.4
          - prometheus-client==0.20.0
