repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: bash -c 'mypy --config-file mypy.ini $(git ls-files "tools/*.py") $(git ls-files "tests/*.py")'
        pass_filenames: false
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: audit-type-ignores
        name: audit type ignores
        entry: python tools/audit_type_ignores.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pytest-quick
        name: pytest quick subset
        entry: bash -c 'pytest -q --maxfail=1'
        language: system
        pass_filenames: false
        stages: [pre-commit]
