apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvhygiene-forensics-pvc
  labels:
    app: kvhygiene
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # set for your cluster
