name: Trivy Scan

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    strategy:
      matrix:
        target: [image, fs]
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Derive short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - name: Derive image tag
        id: meta
        run: |
          echo "tag=cpu-${{ steps.sha.outputs.short_sha }}" >> "$GITHUB_OUTPUT"
          echo "image=${IMAGE_REPO}:cpu-${{ steps.sha.outputs.short_sha }}" >> "$GITHUB_OUTPUT"
      - name: Attempt docker pull (best-effort)
        if: matrix.target == 'image'
        run: |
          docker pull "${{ steps.meta.outputs.image }}" || echo "Image not yet published; continuing with scan attempt."
      - name: Run Trivy (table report)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: ${{ matrix.target }}
          image-ref: ${{ matrix.target == 'image' && steps.meta.outputs.image || '' }}
          format: table
          scanners: vuln,secret
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: '0'
          cache: true
          skip-setup-trivy: false
          output: trivy-${{ matrix.target }}-results.txt
          timeout: 10m
      - name: Upload table results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ matrix.target }}-results
          path: trivy-${{ matrix.target }}-results.txt
      - name: Run Trivy (SARIF report)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: ${{ matrix.target }}
          image-ref: ${{ matrix.target == 'image' && steps.meta.outputs.image || '' }}
          format: sarif
          scanners: vuln
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: '0'
          cache: true
          skip-setup-trivy: false
          output: trivy-${{ matrix.target }}-results.sarif
          timeout: 10m
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ matrix.target }}-results.sarif
        continue-on-error: true
  notify:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Download scan artifacts
        uses: actions/download-artifact@v4
        with:
          path: trivy-reports
      - name: Send Slack Notification
        if: always() && env.SLACK_WEBHOOK != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          echo "Sending Slack notification..."
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"Trivy scan completed. Reports: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" \
            "$SLACK_WEBHOOK" || echo "Slack notification failed or not configured"
      - name: Send Email Notification
        if: always() && env.MAIL_USERNAME != '' && env.MAIL_PASSWORD != ''
        uses: dawidd6/action-send-mail@v3
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ env.MAIL_USERNAME }}
          password: ${{ env.MAIL_PASSWORD }}
          subject: "Trivy Scan Completed - ${{ github.repository }}"
          body: "Trivy scan finished. Reports: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          to: "security-team@example.com"
          from: "ci-bot@example.com"
